version: '3.3'

services:
  nginx:
    image: nginx
    ports:
    - "443:443"
  mariadb:
    image: mysql
    depends_on:
      - nginx
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
  # wordpress:
  #   depends_on:
  #     - mariadb
  #   image: wordpress
  #   volumes:
  #     - wordpress_data:/var/www/html
  #   restart: always
  #   env_file:
  #     - .env
  #   environment:
  #     - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
  #     - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
  #     - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
  #     - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}

volumes:
  db_data: {}
  wordpress_data: {}