version: '3.3'

services:
  nginx:
    image: nginx
    depends_on:
      - wordpress
    build:
      context: ./requirements/nginx
    volumes:
      - word-press:/var/www/html
    networks:
      - 42-network
    ports:
      - "443:443"
    restart: unless-stopped

  mariadb:
    image: mariadb
    build:
      context: ./requirements/mariadb
    volumes:
      - maria-db:/var/lib/mysql
    environment:
      MARIADB_HOST:     ${MARIADB_HOST}
      MARIADB_USER:     ${MARIADB_USER}
      MARIADB_PWD:      ${MARIADB_PWD}
      MARIADB_DB:       ${MARIADB_DB}
      MARIADB_ROOT_PWD: ${MARIADB_ROOT_PWD}
      WP_DATABASE:      ${WP_DATABASE}
      WP_DB_USER:       ${WP_DB_USER}
      WP_DB_PWD:        ${WP_DB_PWD}
      DOMAIN_NAME:      ${DOMAIN_NAME}
      WP_TITLE:         ${WP_TITLE}
      WP_ADMIN:         ${WP_ADMIN}
      WP_ADMIN_PWD:     ${WP_ADMIN_PWD}
      WP_ADMIN_EMAIL:   ${WP_ADMIN_EMAIL}
      WP_USER:          ${WP_USER}
      WP_USER_PWD:      ${WP_USER_PWD}
      WP_USER_EMAIL:    ${WP_USER_EMAIL}
    networks:
      - 42-network
    restart: unless-stopped

  wordpress:
    image: wordpress
    depends_on:
      - mariadb
    environment:
      MARIADB_HOST:     ${MARIADB_HOST}
      MARIADB_USER:     ${MARIADB_USER}
      MARIADB_PWD:      ${MARIADB_PWD}
      MARIADB_DB:       ${MARIADB_DB}
      MARIADB_ROOT_PWD: ${MARIADB_ROOT_PWD}
      WP_DATABASE:      ${WP_DATABASE}
      WP_DB_USER:       ${WP_DB_USER}
      WP_DB_PWD:        ${WP_DB_PWD}
      WP_HOST:          ${WP_HOST}
      WP_TITLE:         ${WP_TITLE}
      WP_ADMIN:         ${WP_ADMIN}
      WP_ADMIN_PWD:     ${WP_ADMIN_PWD}
      WP_ADMIN_EMAIL:   ${WP_ADMIN_EMAIL}
      WP_USER:          ${WP_USER}
      WP_USER_PWD:      ${WP_USER_PWD}
      WP_USER_EMAIL:    ${WP_USER_EMAIL}
    build:
      context: ./requirements/wordpress
    volumes:
      - word-press:/var/www/html    
    networks:
      - 42-network
    restart: unless-stopped

volumes:
  maria-db:
    driver: local
    driver_opts:
      device: /home/mlazzare/data/database
      type: volume
      o: bind
  word-press:
    driver: local
    driver_opts:
      device: /home/mlazzare/data/wordpress
      type: volume
      o: bind

networks:
  42-network:
