version: '3.3'

services:

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wp_volume:/var/www/wordpress
    networks:
      - 42_inception
    restart: unless-stopped

  mariadb:
    image: mysql
    container_name: mariadb
    volumes:
      - database:/var/lib/mysql
    restart: always
    networks:
      - 42_inception

  wordpress:
    depends_on:
      - mariadb
    image: wordpress
    hostname: mlazzare.42.fr
    volumes:
      - wp_volume:/var/www/wordpress
    networks:
      - 42_inception
    restart: always

volumes:
    database:
      driver: local
      driver_opts:
          device: /home/${USER}/data/database
          o: bind
          type: none
    wp_volume:
      driver: local
      driver_opts:
          device: /home/${USER}/data/wordpress
          o: bind
          type: none

networks:
  42_inception: {}
