version: '3.3'
services:
  nginx:
    image: nginx
  mariadb:
    image: mysql
    depends_on:
      - nginx
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=demodb
  wordpress:
    depends_on:
      - mariadb
    image: wordpress
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "3306:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
volumes:
  db_data: {}
  wordpress_data: {}


# services:
#     server:
#         build: 
#             dockerfile: Dockerfile
#             context: ./server 
#         volumes:
#             - /app/node_modules 
#             - ./server:/app
#     nginx:
#         restart: always
#         build: 
#           dockerfile: Dockerfile
#           context: ./controller
#         ports: 
#           - '5000:80'
#     client: 
#         build: 
#             dockerfile: Dockerfile
#             context: ./client
#         volumes:
#             - /app/node_modules 
#             - ./client:/app
#     ports:
#   - "3306:3306"
#   expose:
#     - "3306"